name: kcounter workflow

on: [push]

jobs:
  build:
    name: Build & test
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.6', '3.7', '3.8' ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.5
      with:
        profile: minimal
        toolchain: nightly
        default: true
    - name: Setup Python ${{ matrix.python-version }} environment
      uses: actions/setup-python@v1.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Maturin build
      run: |
        pip install maturin
        maturin build --release --interpreter python
    - name: Install kcounter
      run: pip install target/wheels/*.whl
      shell: bash
    - name: Test
      run: |
        pip install pytest
        pytest
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build-artifact
        path: target/wheels
